/* ============================================================
   BANQUE DE QUESTIONS DE JURY – 200+ questions
   Concours Attaché Territorial – Martinique
   ============================================================ */

/* --- Données : 210 questions catégorisées --- */
window.BANQUE_JURY = [

  /* ── MOTIVATION & PROJET PROFESSIONNEL (25) ─────────────── */
  { cat:'motivation', diff:1, question:'Parlez-moi de vous en 5 minutes.', tips:['Formation Bachelor RH','Expériences significatives','Motivations pour le concours','Projet professionnel dans la FPT','Connaissance de la Martinique'], exemple:'Après mon Bachelor RH qui m\'a donné une solide base en gestion des ressources humaines, j\'ai souhaité mettre ces compétences au service du secteur public…' },
  { cat:'motivation', diff:1, question:'Pourquoi souhaitez-vous devenir Attaché Territorial ?', tips:['Mission de service public','Polyvalence du poste (RH, finances, projets)','Ancrage territorial','Lien avec votre formation','Ambition de contribuer au développement de la Martinique'] },
  { cat:'motivation', diff:2, question:'En quoi votre formation en RH vous prépare-t-elle aux missions d\'un Attaché Territorial ?', tips:['Gestion des ressources humaines (recrutement, carrière, dialogue social)','Connaissance du droit du travail adaptable au statut FPT','Compétences en management d\'équipe','Gestion de projets RH transposable','Maîtrise des outils d\'évaluation et de formation'] },
  { cat:'motivation', diff:1, question:'Quelles sont les qualités essentielles d\'un Attaché Territorial selon vous ?', tips:['Polyvalence et adaptabilité','Rigueur juridique et budgétaire','Sens du service public','Capacité à animer une équipe','Aptitude à rédiger des actes administratifs'] },
  { cat:'motivation', diff:2, question:'Où vous voyez-vous dans 5 ans au sein de la Fonction Publique Territoriale ?', tips:['Progression vers Attaché Principal','Spécialisation (RH, finances, urbanisme)','Prise de responsabilité managériale','Ancrage dans la collectivité martiniquaise','Contribution à des projets structurants'] },
  { cat:'motivation', diff:2, question:'Pourquoi la Martinique et la CTM plutôt qu\'une autre collectivité ?', tips:['Origine et ancrage territorial','Enjeux spécifiques (CTM, collectivité unique)','Projets de développement (PADDM, fonds européens)','Défis démographiques et économiques stimulants','Compétences élargies de la CTM vs collectivité ordinaire'] },
  { cat:'motivation', diff:1, question:'Avez-vous eu des expériences dans le secteur public ?', tips:['Stage, alternance, bénévolat','Missions concrètes réalisées','Liens avec les missions FPT','Apprentissages tirés','Confirmation de la vocation pour le service public'] },
  { cat:'motivation', diff:2, question:'Comment gérez-vous le stress dans votre travail ?', tips:['Planification et priorisation','Décomposition des tâches complexes','Respiration et gestion physique du stress','Expériences passées de gestion de pression','Aptitude au recul et à la prise de perspective'] },
  { cat:'motivation', diff:3, question:'Qu\'est-ce qui vous a convaincu de préparer le concours d\'Attaché plutôt que d\'Adjoint Administratif ou de Rédacteur ?', tips:['Niveau de responsabilité (Catégorie A)','Rôle de conception et de direction','Adéquation avec Bachelor RH (niveau Bac+3)','Ambition de piloter des politiques publiques','Différence A/B/C dans les missions réelles'] },
  { cat:'motivation', diff:2, question:'Comment avez-vous préparé ce concours ?', tips:['Organisation personnelle (planning de révision)','Sources utilisées (CNFPT, manuels, actualités)','Points forts identifiés','Lacunes travaillées','Méthode de révision (fiches, quiz, mises en situation)'] },
  { cat:'motivation', diff:1, question:'Quelles sont vos points forts et vos axes d\'amélioration ?', tips:['Points forts : rigueur, adaptabilité, sens relationnel','Axes d\'amélioration formulés positivement','Exemples concrets pour chaque point','Démarche d\'amélioration continue','Honnêteté et lucidité sur soi-même'] },
  { cat:'motivation', diff:2, question:'Qu\'est-ce que le service public représente pour vous ?', tips:['Égalité, neutralité, continuité (principes SPA)','Mission d\'intérêt général au-delà du profit','Responsabilité vis-à-vis des usagers-citoyens','Fierté de contribuer à la cohésion sociale','Spécificité des valeurs de la FPT vs secteur privé'] },
  { cat:'motivation', diff:3, question:'Comment concevez-vous le rôle d\'un Attaché Territorial dans la hiérarchie administrative ?', tips:['Interface entre direction et agents d\'exécution','Rôle de conception et de conseil','Autonomie dans la mise en œuvre','Responsabilité sur les actes produits','Liens avec les élus et le DGS/DGA'] },
  { cat:'motivation', diff:2, question:'Que feriez-vous si votre supérieur hiérarchique vous demande de faire quelque chose d\'illégal ?', tips:['Obligation de loyauté mais limite légale','Alerte interne (supérieur hiérarchique, DGS)','Devoir d\'information et de conseil','Dispositifs de lanceur d\'alerte (loi Sapin II, CGFP)','Refus motivé par écrit si persistance'] },
  { cat:'motivation', diff:2, question:'Comment gérez-vous un désaccord avec un élu ?', tips:['Respect de la légitimité élue','Rôle de conseil du fonctionnaire','Exposer les risques juridiques clairement','Proposer des alternatives légales','Tracer les échanges (courriers, CR de réunion)'] },
  { cat:'motivation', diff:1, question:'Citez 3 valeurs fondamentales du fonctionnaire territorial.', tips:['Neutralité / Laïcité','Impartialité et égalité de traitement','Probité et intégrité','Discrétion professionnelle','Continuité du service public'] },
  { cat:'motivation', diff:3, question:'Qu\'est-ce qui différencie un Attaché d\'un Directeur dans une collectivité ?', tips:['Grade vs emploi fonctionnel','Attaché : A1-A2 ; Directeur : contractuel ou emploi fonctionnel','Responsabilité hiérarchique plus large du directeur','Attaché : conception, études, instruction','Directeur : pilotage stratégique, direction de service'] },
  { cat:'motivation', diff:2, question:'Expliquez la notion de neutralité du fonctionnaire.', tips:['Interdiction d\'exprimer ses opinions dans l\'exercice des fonctions','Égalité de traitement de tous les usagers','Laïcité de l\'agent public','Distinction entre sphère publique et vie privée','Exceptions : droit syndical et liberté d\'expression hors service'] },
  { cat:'motivation', diff:2, question:'Que ferez-vous si vous constatez une situation de harcèlement dans votre équipe ?', tips:['Obligation d\'alerte et protection du signalant','Procédure RH : DRH, médecin de prévention, ISST','Protection fonctionnelle de l\'agent victime','Enquête administrative diligentée','Sanctions disciplinaires si établi'] },
  { cat:'motivation', diff:1, question:'Êtes-vous prêt à être affecté dans n\'importe quel service de la collectivité ?', tips:['Obligation de mobilité fonctionnelle','Polyvalence de l\'Attaché Territorial','Montrer l\'ouverture à différents services','Exemple : finances, RH, urbanisme, communication','Rappeler les spécialités du cadre d\'emplois attaché'] },
  { cat:'motivation', diff:3, question:'Comment travailleriez-vous avec un agent plus ancien et expérimenté que vous qui conteste votre autorité ?', tips:['Reconnaissance de l\'expérience de l\'agent','Dialogue bienveillant mais affirmatif','Légitimité du grade et de la délégation','Écoute des objections et réponse argumentée','Si persistance : entretien formel, rapport hiérarchique'] },
  { cat:'motivation', diff:2, question:'Qu\'entendez-vous par "devoir de réserve" ?', tips:['Obligation de modération dans l\'expression publique','Différent de la discrétion professionnelle','Plus fort pour les hauts fonctionnaires','Hors service : liberté d\'expression mais prudence','Exemple : expression politique sur les réseaux sociaux'] },
  { cat:'motivation', diff:1, question:'Quelle est la différence entre un agent titulaire et un agent contractuel dans la FPT ?', tips:['Titulaire : nommé dans un grade, statut de fonctionnaire','Contractuel : CDD ou CDI, droit du travail adapté','Accès : concours vs recrutement direct','Rémunération et évolution de carrière différentes','Place des contractuels en expansion : loi 2019'] },
  { cat:'motivation', diff:2, question:'Pourquoi le concours est-il le mode de recrutement de référence dans la FPT ?', tips:['Principe d\'égalité d\'accès aux emplois publics','Sélection sur mérite et compétences','Indépendance vis-à-vis des réseaux politiques','Garantie de qualité des recrutements','Exceptions légales : contractuels, emplois fonctionnels'] },
  { cat:'motivation', diff:1, question:'Quels sont les 3 versants de la Fonction Publique ?', tips:['Fonction Publique d\'État (FPE)','Fonction Publique Territoriale (FPT)','Fonction Publique Hospitalière (FPH)','Principes communs : Loi du 13 juillet 1983','Spécificités de la FPT : CDG, CNFPT, paritarisme'] },

  /* ── ENVIRONNEMENT TERRITORIAL (28) ─────────────────────── */
  { cat:'territorial', diff:1, question:'Quelle est la différence entre déconcentration et décentralisation ?', tips:['Déconcentration : au sein de l\'État (préfet = même personne morale)','Décentralisation : personnes morales distinctes (collectivités)','Contrôle a priori (tutelle) vs a posteriori (légalité)','Exemple : préfet = déconcentration ; CTM = décentralisation','Article 1er Constitution : "organisation décentralisée"'] },
  { cat:'territorial', diff:1, question:'Quelles sont les trois grandes lois de décentralisation ?', tips:['Acte I : Loi Defferre 2 mars 1982','Acte II : Révision const. 28 mars 2003 + Lois Raffarin 2004','Acte III : Loi MAPTAM 2014 + Loi NOTRe 2015','Tendances : suppression clause de compétence générale (CG/Région)','Rôle croissant des métropoles et intercommunalités'] },
  { cat:'territorial', diff:2, question:'Quelles sont les compétences obligatoires d\'une commune ?', tips:['État civil, police municipale, urbanisme (PLU)','Enseignement (écoles primaires, cantine)','Action sociale de proximité (CCAS)','Voirie communale, eau/assainissement','Développement économique local'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce qu\'un EPCI ? Citez les principaux types.', tips:['Établissement Public de Coopération Intercommunale','Communauté de Communes (zones rurales)','Communauté d\'Agglomération (50 000+ hab)','Communauté Urbaine (250 000+ hab)','Métropole (400 000+ hab, compétences élargies)'] },
  { cat:'territorial', diff:3, question:'Qu\'est-ce que la clause de compétence générale et pourquoi a-t-elle été supprimée pour les régions et départements ?', tips:['Capacité d\'une collectivité à agir dans tout domaine d\'intérêt local','Supprimée pour régions et départements par Loi NOTRe 2015','Maintenue pour les communes','Objectif : clarifier le partage des compétences, éviter les doublons','Conséquence : spécialisation fonctionnelle de chaque niveau'] },
  { cat:'territorial', diff:2, question:'Quelles sont les compétences principales d\'une région ?', tips:['Développement économique (SRDEII)','Formation professionnelle et apprentissage','Lycées (construction et entretien)','Transport ferroviaire régional (TER)','Aménagement du territoire (SRADDET)','Fonds européens FEDER/FSE+ en tant qu\'autorité de gestion'] },
  { cat:'territorial', diff:2, question:'Quelles sont les compétences principales d\'un département ?', tips:['Action sociale : RSA, APA, protection de l\'enfance','Collèges (construction et entretien)','Routes départementales','SDIS (incendie et secours)','Aides aux communes rurales (DETR)'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que le contrôle de légalité ?', tips:['Contrôle a posteriori des actes des collectivités','Exercé par le préfet (délai 2 mois pour déférer)','Saisine du Tribunal Administratif','Acte reste exécutoire en attendant (pas d\'effet suspensif en principe)','Réforme 1982 : fin de la tutelle a priori'] },
  { cat:'territorial', diff:1, question:'Quelle est la composition d\'un conseil municipal ?', tips:['Élus au suffrage universel direct','Nombre d\'élus selon taille de la commune (7 à 69 membres)','Scrutin : plurinominal majoritaire (<1000 hab) ou proportionnel de liste (>1000)','Mandat de 6 ans','Élit le maire en son sein'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que la Chambre Régionale des Comptes (CRC) ?', tips:['Juridiction administrative financière','Contrôle la régularité des comptes et la gestion des collectivités','Recommandations non contraignantes sur la gestion','Peut saisir le Parquet si irrégularités pénales','En Martinique : CRAC (Chambre Régionale Antilles-Guyane)'] },
  { cat:'territorial', diff:2, question:'Expliquez le rôle du préfet en matière de contrôle de légalité.', tips:['Représentant de l\'État dans le département/région','Reçoit les actes obligatoirement transmis (délibérations, arrêtés)','2 mois pour déférer au TA','Peut demander suspension d\'urgence (référé)','Rôle pédagogique préalable (conseil, prévention des irrégularités)'] },
  { cat:'territorial', diff:3, question:'Qu\'est-ce que l\'article 72 de la Constitution ?', tips:['Collectivités : communes, départements, régions, collectivités à statut particulier, COM','Principe de libre administration par conseils élus','Représentant de l\'État : délégué du Gouvernement (préfet)','Subsidiarité : décision au niveau le plus pertinent','Réforme 2003 : droit à l\'expérimentation'] },
  { cat:'territorial', diff:2, question:'Quelle est la différence entre une compétence exclusive et une compétence partagée ?', tips:['Compétence exclusive : une seule collectivité (ex. RSA = département)','Compétence partagée : plusieurs niveaux peuvent intervenir','Ex. : culture, sport, tourisme = partagées entre communes, départs., régions','Collectivité chef de file : coordonne l\'exercice','Objectif Loi NOTRe : clarifier pour réduire doublons'] },
  { cat:'territorial', diff:1, question:'Qu\'est-ce que la Dotation Globale de Fonctionnement (DGF) ?', tips:['Principal concours financier de l\'État aux collectivités','~27 milliards d\'euros/an pour l\'ensemble des collectivités','Composante de péréquation : rééquilibre les inégalités','DGF forfaitaire + DGF de péréquation','Tendance à la baisse depuis 2014 (contrainte budgétaire State)'] },
  { cat:'territorial', diff:3, question:'Qu\'est-ce que le CGCT et quelle est son importance ?', tips:['Code Général des Collectivités Territoriales','Codifie l\'ensemble des règles applicables aux collectivités','Issu de la loi ATR 1992 puis des lois successives','Comprend les règles d\'organisation, compétences, finances, personnel','Référence juridique quotidienne pour tout Attaché Territorial'] },
  { cat:'territorial', diff:2, question:'Expliquez le principe de subsidiarité dans l\'organisation territoriale.', tips:['Décisions prises au niveau le plus proche des citoyens','Inscrit dans l\'art. 72 Constitution depuis 2003','Aussi dans le droit européen (art. 5 TUE)','Justification du transfert de compétences vers les collectivités','Limite : certaines compétences restent nationales par nature'] },
  { cat:'territorial', diff:1, question:'Combien y a-t-il de communes en France ?', tips:['Environ 34 946 communes','Dont 96 en métropole + territoires d\'outre-mer','34 communes en Martinique','Tendance au regroupement via intercommunalité','Taille très hétérogène : de 1 à 2,2 millions d\'habitants'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que le pacte de gouvernance d\'une intercommunalité ?', tips:['Document définissant les relations entre EPCI et communes membres','Obligatoire depuis Loi Engagement et Proximité 2019','Précise les délégations de compétences, conférences des maires','Renforce la place des communes dans l\'EPCI','Réponse politique à la crise des "grandes fusions" post-2015'] },
  { cat:'territorial', diff:2, question:'Expliquez le rôle du CNFPT.', tips:['Centre National de la Fonction Publique Territoriale','Organisme paritaire de formation des agents territoriaux','FIA (formation initiale d\'application) obligatoire pour les lauréats','Formation continue tout au long de la carrière','Antenne Antilles-Guyane pour les DROM'] },
  { cat:'territorial', diff:1, question:'Qu\'est-ce qu\'un Centre de Gestion (CDG) ?', tips:['Organisme de gestion mutualisée des ressources humaines des petites collectivités','Organise les concours et examens professionnels','Gère les CAP, CST, instances de dialogue social','Mise à disposition d\'agents, conseil statutaire','CDG 972 pour la Martinique'] },
  { cat:'territorial', diff:3, question:'Qu\'est-ce que le principe d\'autonomie financière des collectivités ?', tips:['Art. 72-2 Constitution : ressources propres représentant une part déterminante','Liberté de fixer les taux fiscaux dans certaines limites','Recettes fiscales + dotations + emprunts','Tendance à l\'érosion (transferts de compétences sans ressources suffisantes)','Lien avec le principe de libre administration'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que la loi NOTRe et ses principales dispositions ?', tips:['Loi du 7 août 2015 portant Nouvelle Organisation Territoriale de la République','Suppression clause de compétence générale des départs. et régions','Renforcement des régions (économie, transport) et des communes/EPCI (social)','Transfert de certaines routes nationales aux régions','Fusion des régions (13 régions métropolitaines)'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que le SRADDET ?', tips:['Schéma Régional d\'Aménagement, de Développement Durable et d\'Égalité des Territoires','Document de planification de la région','Prescriptions opposables aux SCoT (et donc aux PLU)','Remplace SRCE, SRCAE, SRIT, SRADT','En Martinique : remplacé par PADDM (Plan d\'Aménagement Durable de la Martinique)'] },
  { cat:'territorial', diff:1, question:'Expliquez la différence entre un arrêté municipal et une délibération du conseil municipal.', tips:['Arrêté municipal : acte unilatéral du maire (pouvoir propre)','Délibération : décision collective du conseil municipal','Exemples arrêté : police, exécution de décisions du conseil','Exemples délibération : budget, marchés importants, règlement','Publicité et transmissibilité au préfet pour les deux'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce qu\'un service public à caractère industriel et commercial (SPIC) ?', tips:['SPA : service public administratif (règles de droit public)','SPIC : activités proches du secteur privé (tarifs, usagers-clients)','Gestion en régie ou DSP (délégation de service public)','Ex. SPIC : eau, transports, déchets, camping municipal','Conséquence : droit privé applicable aux relations avec les usagers'] },
  { cat:'territorial', diff:3, question:'Qu\'est-ce que la mutualisation des services entre collectivités ?', tips:['Partage de services et de personnels entre EPCI et communes membres','Obligatoire : rapport annuel sur la mutualisation (Loi NOTRe)','Objectif : réduire les coûts, améliorer la qualité','Formes : services communs, mise à disposition, groupements d\'achats','Exemple : service informatique mutualisé entre CTM et communes'] },
  { cat:'territorial', diff:2, question:'Qu\'est-ce que le pouvoir réglementaire local ?', tips:['Droit des collectivités d\'édicter des règlements locaux','Limité : ne peut contrevenir aux lois et règlements nationaux','Exemples : règlement intérieur, stationnement, bruit','Depuis 2003 : pouvoir d\'adaptation législative (art. 73 Constitution)','En Martinique : habilitation CTM à adapter les lois (art. 73 al. 3-5)'] },
  { cat:'territorial', diff:1, question:'Qu\'est-ce que le Conseil Économique, Social et Environnemental Régional (CESER) ?', tips:['Instance consultative régionale (économie, social, environnement)','Avis obligatoire sur le budget, les schémas régionaux','Composé de représentants socio-économiques, associations, syndicats','Pas de pouvoir décisionnel : avis consultatifs','En Martinique : CESECEM (Conseil Économique, Social, Environnemental, Culturel de la Martinique)'] },

  /* ── MARTINIQUE & CTM (32) ───────────────────────────────── */
  { cat:'martinique', diff:1, question:'Qu\'est-ce que la CTM et en quoi est-elle différente d\'une région ordinaire ?', tips:['Collectivité Territoriale de Martinique = collectivité unique','Fusion du Conseil Général et du Conseil Régional','Loi du 27 juillet 2011, opérationnelle depuis 22 déc. 2015','Statut art. 73 Constitution (DROM) mais collectivité sui generis','Compétences cumulées : sociales (ex-CG) + économiques (ex-CR)'] },
  { cat:'martinique', diff:1, question:'Quels sont les organes de gouvernance de la CTM ?', tips:['Assemblée de Martinique : 51 membres élus','Conseil Exécutif : Président + 8 conseillers exécutifs','Président de l\'Assemblée (distinct du Président du CE)','CESECEM : instance consultative','CTAP : Conférence Territoriale de l\'Action Publique'] },
  { cat:'martinique', diff:2, question:'Comment se déroule l\'élection de l\'Assemblée de Martinique ?', tips:['Scrutin de liste proportionnel à 2 tours','Prime majoritaire au premier tour (1/3 des sièges si majorité absolue)','Mandat de 5 ans','51 conseillers élus','Dernières élections : décembre 2021, réélection de Serge Letchimy'] },
  { cat:'martinique', diff:2, question:'Quelles sont les principales compétences de la CTM ?', tips:['Action sociale : RSA, APA, protection enfance (ex-CG)','Développement économique : SRDEII, PME, tourisme (ex-CR)','Aménagement : PADDM, urbanisme','Routes, transports interurbains','Fonds européens : autorité de gestion FEDER, FSE+, FEADER','Coopération régionale caribéenne'] },
  { cat:'martinique', diff:1, question:'Qu\'est-ce que l\'octroi de mer ?', tips:['Taxe douanière sur les importations en Martinique','Institué depuis l\'époque coloniale, réformé régulièrement','~200 M€/an de recettes pour les collectivités martiniquaises','Réparti entre CTM et communes','Autorisé par dérogation UE, régime expirant à réviser','Controversé : protection des productions locales vs cherté de la vie'] },
  { cat:'martinique', diff:2, question:'Quel est le taux de chômage en Martinique et quelles en sont les causes ?', tips:['~17% (vs 7,3% en métropole)','Jeunes : >40% de chômage','Causes : économie peu diversifiée, dépendance aux importations','Désindustrialisation, fuite des cerveaux (brain drain)','Poids du secteur public comme principal employeur'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que le chlordécone et quelles sont ses conséquences ?', tips:['Pesticide utilisé dans les bananeraies jusqu\'en 1993 (interdit en France en 1990)','Contamination des sols, eaux, aliments pour des décennies','Enjeu de santé publique majeur : cancer de la prostate, perturbateur endocrinien','Plan chlordécone IV (2021-2027) : dépollution, recherche, indemnisation','Revendication d\'une reconnaissance de responsabilité de l\'État'] },
  { cat:'martinique', diff:1, question:'Quelle est la démographie de la Martinique ?', tips:['~360 000 habitants (en déclin depuis 2010)','Vieillissement accéléré : 1/3 des habitants >60 ans en 2030','Exode vers la métropole (brain drain) : -15 000 hab en 10 ans','Densité : ~319 hab/km²','34 communes, superficie 1 128 km²'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que le PADDM ?', tips:['Plan d\'Aménagement et de Développement Durable de la Martinique','Document de planification territorialé de la CTM','Remplace le SRADDET et le SAR (Schéma d\'Aménagement Régional)','Contient les objectifs de développement durable','Horizon 2030-2050'] },
  { cat:'martinique', diff:2, question:'Quels sont les enjeux du secteur agricole en Martinique ?', tips:['Déclin de la banane (concurrence mondiale, prix bas)','Diversification nécessaire (cultures vivrières, maraîchage)','Rhum agricole AOC : produit d\'excellence et d\'exportation','Contamination chlordécone : restrictions sur certains terrains','Enjeu de souveraineté alimentaire (forte dépendance aux importations)'] },
  { cat:'martinique', diff:2, question:'Décrivez les fonds européens mobilisables en Martinique.', tips:['RUP (Région Ultra-Périphérique) : accès privilégié aux fonds','FEDER : 2021-2027, ~450 M€ (infrastructure, entreprises, énergie)','FSE+ : formation, emploi, inclusion (~150 M€)','FEADER : agriculture et ruralité','REACT-EU et Next Generation EU : fonds post-COVID','CTM = autorité de gestion déléguée par l\'État'] },
  { cat:'martinique', diff:1, question:'Quels sont les principaux risques naturels en Martinique ?', tips:['Cyclones (zone tropicale, saison juin-novembre)','Séismes (arc volcanique des Antilles)','Éruptions volcaniques : montagne Pelée (1902 – 30 000 morts)','Tsunamis','Glissements de terrain, inondations','CTM : Plan de prévention des risques (PPRN), PPRL (littoral)'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que le Plan Martinique Emploi Compétences (PMEC) ?', tips:['Programme pluriannuel de développement de l\'emploi et des compétences','Financé par CTM, État, fonds européens','Dispositifs d\'insertion professionnelle des jeunes','Formation en alternance, contrats aidés','Objectif : réduire le chômage endémique (>17%)'] },
  { cat:'martinique', diff:3, question:'Expliquez la coopération régionale de la Martinique dans la Caraïbe.', tips:['CTM membre de l\'OECO (Organisation des États de la Caraïbe Orientale)','Participation à la CARICOM (observateur)','Accords avec les pays voisins (Sainte-Lucie, Dominique, Trinité)','Enjeu économique : échanges commerciaux, tourisme','Enjeu institutionnel : intégration régionale caribéenne vs appartenance européenne'] },
  { cat:'martinique', diff:2, question:'Quelle est l\'histoire institutionnelle de la Martinique ?', tips:['1635 : colonisation française','1848 : abolition de l\'esclavage (Victor Schœlcher)','1946 : départementalisation (loi Césaire-Monnerville)','1974 : région + département bicéphale','2010 : référendum OUI (68,3%) pour la collectivité unique','2015 : CTM opérationnelle (élections 22 décembre)'] },
  { cat:'martinique', diff:2, question:'Quels sont les enjeux de l\'eau potable en Martinique ?', tips:['Réseau vieillissant avec pertes importantes (>50% dans certains secteurs)','Service géré par la SICSM ou SME (Société Martiniquaise des Eaux)','Enjeu de remise aux normes et d\'investissement','Financement européen FEDER mobilisable','Lien avec la crise de l\'eau (coupures récurrentes)'] },
  { cat:'martinique', diff:3, question:'Comment fonctionne le contrôle budgétaire de la CTM ?', tips:['CRAC (Chambre Régionale des Comptes Antilles-Guyane) pour le contrôle judiciaire','Préfet de Martinique pour le contrôle de légalité','Instruction M57 depuis 2024 (référentiel comptable unifié)','Obligation de vote du budget en équilibre réel','Capacité de désendettement : ratio dette/recettes surveillé'] },
  { cat:'martinique', diff:1, question:'Qui est actuellement Président du Conseil Exécutif de la CTM ?', tips:['Serge Letchimy, réélu en décembre 2021','Leader du Mouvement pour le Devoir de Mémoire','Anciennement Président du Conseil Régional','Avant lui : Alfred Marie-Jeanne (1er président de la CTM, 2015)','À noter : Président de l\'Assemblée et Président du CE sont distincts'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que la politique de l\'eau en Martinique et quels sont ses enjeux ?', tips:['Eau potable : défis d\'infrastructure, vétusté du réseau','Contamination des captages (nitrates, pesticides dont chlordécone)','Compétence : CTM + communes (GEMAPI : gestion milieux aquatiques)','Enjeu financier : investissements massifs nécessaires','Plans de gestion des risques d\'inondation (PGRI)'] },
  { cat:'martinique', diff:2, question:'Décrivez les politiques de développement touristique de la Martinique.', tips:['~1,5 M visiteurs/an (croisières + séjours)','Schéma de développement touristique porté par la CTM','Atouts : nature, culture, gastronomie, plages','Faiblesses : infrastructure hôtelière vieillissante, concurrence caribéenne','Eco-tourisme et tourisme culturel : enjeux de diversification'] },
  { cat:'martinique', diff:3, question:'Qu\'est-ce que l\'article 73 de la Constitution et quelles sont les habilitations législatives de la Martinique ?', tips:['Art. 73 : Droit applicable avec les adaptations nécessaires','Possibilité pour la CTM de demander habilitation à adapter les lois','Adoptée par l\'Assemblée de Martinique + décret du PM','Exemples : fiscalité locale (octroi de mer), formation professionnelle','Distinction avec art. 74 (COM à statut autonome)'] },
  { cat:'martinique', diff:2, question:'Quelles sont les politiques de lutte contre la pauvreté en Martinique ?', tips:['Taux de pauvreté ~30% (3× la moyenne nationale)','RSA : ~45 000 bénéficiaires en Martinique','Politiques CTM : insertion, fonds d\'aide sociale','Rôle de la CGSS (équivalent CAF/URSSAF) pour les prestations','Fonds Européens FSE+ pour l\'insertion et la formation'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que le Plan Énergie Martinique (PEM) et ses objectifs ?', tips:['Objectif : 100% énergies renouvelables d\'ici 2030','Solaire photovoltaïque, éolien, géothermie, houle','Réduire la dépendance aux hydrocarbures importés','Portage : CTM + EDF Martinique + État','Fonds européens FEDER pour les investissements énergétiques'] },
  { cat:'martinique', diff:1, question:'Quels sont les 4 EPCI de Martinique ?', tips:['CACEM : Communauté d\'Agglomération du Centre de la Martinique (Fort-de-France)','CAESM : Communauté d\'Agglomération de l\'Espace Sud de la Martinique','CAP Nord Martinique : Communauté d\'Agglomération du Pays Nord Martinique','ESPACE SUD : + petites communes','34 communes réparties entre ces 4 EPCI'] },
  { cat:'martinique', diff:3, question:'Comment la Martinique s\'adapte-t-elle au changement climatique ?', tips:['PCAET (Plan Climat-Air-Énergie Territorial) de la CTM','Risques accrus : montée des eaux, intensité cyclonique, érosion côtière','Adaptation de l\'agriculture (chlordécone + changement climatique)','Biodiversité : forêts tropicales, mangroves, récifs coralliens menacés','Financement : fonds Life+, FEDER, politique nationale d\'adaptation (PNACC)'] },
  { cat:'martinique', diff:2, question:'Qu\'est-ce que le décrochage démographique de la Martinique et comment y répondre ?', tips:['Perte de population depuis 2010 (-15 000 en 10 ans)','Émigration des jeunes actifs vers la métropole (brain drain)','Vieillissement : 1/3 >60 ans en 2030','Réponses : attractivité territoriale, retour des compétences, emploi local','Enjeu pour les services publics : EHPAD, aide à domicile, école'] },
  { cat:'martinique', diff:2, question:'Comment fonctionne l\'aide sociale en Martinique ?', tips:['RSA géré par la CTM (compétence ex-Conseil Général)','APA (allocation personnalisée d\'autonomie) : vieillissement accéléré','Protection de l\'enfance : ASE (Aide Sociale à l\'Enfance)','Personnes handicapées : MDPH Martinique','Financement : CTM + CGSS + fonds européens FSE+'] },
  { cat:'martinique', diff:1, question:'Qu\'est-ce que la CGSS de Martinique ?', tips:['Caisse Générale de Sécurité Sociale','Régime général + allocations familiales + gestion des AT/MP (tout-en-un)','Particularité outre-mer : organisme unique (vs séparation métropole)','Gère aussi le RSA pour la part nationale','Interlocuteur unique pour les assurés et les employeurs martiniquais'] },
  { cat:'martinique', diff:3, question:'Qu\'est-ce que la loi ÉGALIM et son impact sur la production locale martiniquaise ?', tips:['Loi du 30 octobre 2018 pour l\'équilibre des relations commerciales agricoles','Obligation de 50% de produits durables/20% bio en restauration collective','Opportunité pour les produits locaux martiniquais','Défi : atteindre les volumes et certifications nécessaires','Rôle de la CTM : soutien à l\'agriculture locale, circuits courts'] },
  { cat:'martinique', diff:2, question:'Quels sont les enjeux de la mobilité en Martinique ?', tips:['Forte dépendance à la voiture individuelle','Embouteillages chroniques autour de Fort-de-France','Transport en commun : bus CTM, projets de BHNS (Bus Haut Niveau Service)','Caravelle (ex-projet de tramway) : réévalué','TCSP (Transport en Commun en Site Propre) : enjeu de financcement FEDER'] },

  /* ── RH & MANAGEMENT (28) ────────────────────────────────── */
  { cat:'rh', diff:2, question:'Un agent de votre équipe accumule les absences injustifiées. Quelle démarche adoptez-vous ?', tips:['1. Entretien individuel informel – comprendre les causes','2. Identifier : problème personnel, médical, relationnel ou désengagement','3. Orienter vers le médecin de prévention si cause médicale','4. Si comportemental : avertissement écrit, procédure disciplinaire','5. Rédiger un rapport à la DRH'] },
  { cat:'rh', diff:2, question:'Expliquez la procédure de sanction disciplinaire dans la FPT.', tips:['4 groupes de sanctions (1er : avertissement/blâme ; 4ème : révocation)','Droit de la défense : agent consulte son dossier','Consultation du Conseil de Discipline (CAP) au-delà du blâme','Principe du contradictoire : agent entend et répond','Décision motivée et notifiée par écrit'] },
  { cat:'rh', diff:1, question:'Qu\'est-ce que la protection fonctionnelle ?', tips:['Obligation de l\'employeur de protéger l\'agent en cas d\'attaque liée à ses fonctions','Couverture juridique (défense pénale/civile)','Aide psychologique, financière si menace','Condition : faute de service (pas personnelle grave)','S\'applique aussi aux élus depuis loi 2021'] },
  { cat:'rh', diff:2, question:'Vous devez recruter un Attaché pour votre service. Décrivez la procédure.', tips:['Recrutement par concours (externe, interne, 3ème voie)','Ou recrutement contractuel sur emploi non pourvu','Publication du poste sur la Bourse de l\'Emploi Public + site collectivité','Constitution du jury','Arrêté de nomination, période de stage (1 an), titularisation'] },
  { cat:'rh', diff:3, question:'Qu\'est-ce que le Comité Social Territorial (CST) et quel est son rôle ?', tips:['Instance de dialogue social créée par la loi de transformation publique 2019','Remplace le CTP (Comité Technique) et fusionne avec CHSCT','Compétences : organisation, fonctionnement, conditions de travail','Composition paritaire (représentants élus + représentants syndicaux)','Consulté sur les restructurations, plans de formation, règlements intérieurs'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que le Compte Personnel de Formation (CPF) dans la FPT ?', tips:['25 heures par an (50h pour agents non qualifiés), plafonné à 150h (400h)','Financement : collectivité employeur + CNFPT','Formations permettant l\'évolution professionnelle','Mobilisable à la demande de l\'agent','Lien avec le droit individuel à la formation (DIF devenu CPF)'] },
  { cat:'rh', diff:2, question:'Expliquez les différences entre mutation, détachement et mise à disposition.', tips:['Mutation : changement de poste, même fonction publique, définitif','Détachement : maintien dans le grade d\'origine, autres fonctions, durée déterminée','Mise à disposition : agent reste rémunéré par d\'origine, travaille pour une autre entité','Intégration directe : possible entre les versants (loi 2019)','Toutes nécessitent l\'accord de l\'agent et/ou des deux employeurs'] },
  { cat:'rh', diff:2, question:'Comment mettez-vous en place un entretien professionnel ?', tips:['Obligatoire annuellement (remplace la notation depuis 2014-2015)','Bilan de l\'année : objectifs atteints ou non','Fixation des objectifs N+1','Identification des besoins de formation','CR signé par les deux parties, versé au dossier'] },
  { cat:'rh', diff:3, question:'Que faire face à une suspicion de harcèlement moral dans votre équipe ?', tips:['Ne pas minimiser, prendre en charge avec diligence','Recueil de témoignages (confidentialité)','Orienter la victime vers DRH, médecin de prévention, ISST','Ouverture d\'une enquête administrative','Protection de la victime (réaffectation temporaire si nécessaire)','Sanctions si harcèlement établi'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que la GPEEC dans la FPT ?', tips:['Gestion Prévisionnelle des Emplois, des Effectifs et des Compétences','Anticiper les évolutions des besoins RH (départs retraite, nouvelles compétences)','Outils : cartographie des emplois, référentiel de compétences','Plans pluriannuels de recrutement et de formation','Spécificité Martinique : brain drain et attractivité des postes'] },
  { cat:'rh', diff:1, question:'Qu\'est-ce que le droit de grève dans la FPT ?', tips:['Reconnu constitutionnellement (Préambule 1946)','Encadré par la loi (préavis 5 jours, service minimum obligatoire)','Interdit aux policiers, gendarmes, magistrats','Service minimum dans les transports, écoles (loi 2007/2008)','Retenue sur salaire (1/30ème par journée de grève)'] },
  { cat:'rh', diff:2, question:'Comment conduire un changement organisationnel dans votre service ?', tips:['Diagnostic initial : pourquoi changer, avec qui, comment','Communication précoce et transparente sur les raisons','Association des agents à la conception (participation)','Formation pour accompagner les nouvelles pratiques','Évaluation régulière et ajustements','Rôle clé du manager de proximité'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que le télétravail dans la FPT et comment l\'encadrez-vous ?', tips:['Droit depuis le décret du 11 février 2016, renforcé post-COVID','Max 3 jours/semaine en règle générale','Accord de télétravail (collectif ou individuel)','Équipement informatique fourni par l\'employeur','Droit à la déconnexion, respect du temps de travail'] },
  { cat:'rh', diff:3, question:'Comment construire un plan de formation pluriannuel pour une collectivité ?', tips:['Recueil des besoins : entretiens professionnels, projets de service','Analyse des compétences existantes vs besoins futurs','Priorisation selon le budget et la stratégie RH','Partenariat avec le CNFPT (formations obligatoires FIA incluses)','Évaluation de la formation (Kirkpatrick : réaction, apprentissage, comportement, résultats)'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que la responsabilité pénale d\'un fonctionnaire ?', tips:['Faute personnelle : engage la responsabilité personnelle (civile et/ou pénale)','Faute de service : engage la responsabilité de l\'administration','La frontière : intentionnalité, gravité, contexte','Protection fonctionnelle ne joue pas pour la faute personnelle détachable','Exemples : favoritisme, prise illégale d\'intérêt, corruption'] },
  { cat:'rh', diff:1, question:'Quelles sont les obligations déontologiques d\'un fonctionnaire territorial ?', tips:['Obéissance hiérarchique (limite : illégalité manifeste ou crime)','Neutralité et impartialité','Discrétion professionnelle et secret professionnel','Obligation de réserve (expression publique modérée)','Probité : pas de conflits d\'intérêts, pas d\'enrichissement personnel','Laïcité'] },
  { cat:'rh', diff:2, question:'Expliquez les motifs légaux de licenciement d\'un agent contractuel de la FPT.', tips:['Insuffisance professionnelle','Comportement incompatible avec le bon fonctionnement du service','Transformation du poste (suppression)','Refus d\'une modification substantielle (si motif valide)','Procédure : entretien préalable, délai de préavis, motivation écrite'] },
  { cat:'rh', diff:3, question:'Qu\'est-ce que l\'égalité professionnelle F/H dans la FPT ?', tips:['Obligation légale (loi du 12 mars 2012, renforcée 2019)','Rapport sur la situation comparée des F/H','Plan d\'action égalité professionnelle','Nominations aux postes d\'encadrement supérieur : 40% min de chaque sexe','Ecart de rémunération à résorber (primes/échelon)'] },
  { cat:'rh', diff:2, question:'Comment gérer un conflit entre deux membres de votre équipe ?', tips:['Entretiens individuels séparés pour comprendre chaque point de vue','Identification des faits vs perceptions','Réunion de médiation si pertinent (ou médiateur externe)','Rappel des règles professionnelles et du respect mutuel','Suivi post-médiation, formaliser les engagements réciproques'] },
  { cat:'rh', diff:1, question:'Qu\'est-ce que la formation initiale d\'application (FIA) dans la FPT ?', tips:['Obligatoire pour tout lauréat de concours Catégorie A (Attaché)','Organisée par le CNFPT (durée variable selon cadre d\'emploi)','Associe formation théorique et pratique professionnelle','Compte-rendu de stage validé','Non-réalisation = radiation des cadres possible'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que la Commission Administrative Paritaire (CAP) ?', tips:['Instance paritaire (représentants de l\'employeur + syndicats)','Compétente pour les décisions individuelles : avancement, promotion, détachement','Consultée obligatoirement dans certains cas (refus de mutation, sanction)','Réforme 2019 : attribution réduite, suppression du rôle dans l\'avancement d\'échelon','Remplacée pour certaines décisions par l\'entretien professionnel'] },
  { cat:'rh', diff:2, question:'Expliquez ce qu\'est un tableau d\'avancement et la promotion de grade.', tips:['Tableau d\'avancement : liste d\'agents proposés à la promotion par la CAP puis l\'assemblée','Critères : ancienneté, valeur professionnelle (entretien)','Promotion au choix (tableau d\'avancement) vs avancement d\'échelon (ancienneté)','Ratio promus/promouvables fixé par délibération','En pratique : sélection compétitive basée sur l\'entretien pro.'] },
  { cat:'rh', diff:3, question:'Qu\'est-ce que l\'obligation de mobilité pour les fonctionnaires ? Peut-on refuser une mutation ?', tips:['Principe : l\'agent s\'engage à servir où l\'intérêt du service l\'exige','Refus de poste légal possible si : motifs familiaux graves, raisons de santé','Mais l\'autorité territoriale peut prononcer l\'abandon de poste si refus abusif','Distinction : mutation d\'office (disciplinaire) vs mutation dans l\'intérêt du service','Principe du reclassement si suppression de poste'] },
  { cat:'rh', diff:2, question:'Comment vous y prendriez-vous pour former un jeune agent nouvellement recruté ?', tips:['Livret d\'accueil : présentation de la collectivité, organigramme, procédures','Désignation d\'un tuteur ou référent','Entretien de prise de poste : clarification des missions, objectifs des 3 premiers mois','Plan de formation individualisé (FIA CNFPT + formation interne)','Points réguliers (hebdomadaire puis mensuel) les premiers mois'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que la prise illégale d\'intérêt et comment l\'éviter ?', tips:['Délit pénal : art. 432-12 Code pénal','Fonctionnaire ayant un intérêt privé dans une affaire dont il a la charge','Exemple : passer un marché à son propre prestataire','Prévention : déclaration d\'intérêts (HATVP), déport si conflit d\'intérêt','Peine : 5 ans d\'emprisonnement + 500 000€ d\'amende'] },
  { cat:'rh', diff:2, question:'Qu\'est-ce que le plan de prévention des risques psychosociaux (RPS) ?', tips:['Risques professionnels liés au stress, burnout, harcèlement, violence','Obligation d\'évaluation dans le Document Unique (DUERP)','CST et médecin de prévention impliqués','Plan d\'action : management bienveillant, charge de travail, organisation','ISST (Inspecteur Santé Sécurité Travail) : contrôle externe'] },
  { cat:'rh', diff:1, question:'Quelle est la durée légale du temps de travail dans la FPT ?', tips:['1607 heures/an (régime général, réforme 2001)','Des collectivités avaient maintenu des régimes inférieurs','Loi du 6 août 2019 (Transformation publique) : retour au droit commun 1607h','Compte épargne-temps (CET) : report des jours non consommés','Temps de travail des agents à temps partiel au prorata'] },
  { cat:'rh', diff:3, question:'Qu\'est-ce que le rapport Thiriez et ses préconisations sur la haute fonction publique ?', tips:['Rapport de Frédéric Thiriez (2020) sur la haute fonction publique','Proposait une "ENA réformée" avec ouverture sociale accrue','Création de l\'INSP (Institut National du Service Public) en 2022','Fusion de l\'ENA + IRA + écoles de service public','Enjeu : diversification sociale et géographique des hauts fonctionnaires'] },

  /* ── FINANCES PUBLIQUES (25) ─────────────────────────────── */
  { cat:'finances', diff:1, question:'Quels sont les 6 principes budgétaires applicables aux collectivités territoriales ?', tips:['1. Annualité : budget pour 1 an','2. Unité : un seul document budgétaire','3. Universalité : toutes recettes et dépenses (non compensation)','4. Équilibre réel (contrainte forte pour les collectivités)','5. Sincérité : évaluations sincères','6. Spécialité : crédits votés par nature ou programme'] },
  { cat:'finances', diff:2, question:'Quelle est la différence entre la section de fonctionnement et la section d\'investissement ?', tips:['Fonctionnement : dépenses courantes (personnel 55%, achats, subventions)','Investissement : dépenses durables (travaux, emprunts, équipements)','Équilibre de chaque section obligatoire (règle d\'or)','Autofinancement : excédent fonctionnement → investissement','Le recours à l\'emprunt n\'est autorisé que pour financer l\'investissement'] },
  { cat:'finances', diff:2, question:'Expliquez le cycle de la dépense publique.', tips:['1. Engagement : création de l\'obligation juridique de payer','2. Liquidation : vérification du service fait et du montant','3. Mandatement (ordonnancement) : autorisation de payer','4. Paiement : exécution par le comptable public (Trésor)','Séparation ordonnateur/comptable : règle fondamentale'] },
  { cat:'finances', diff:2, question:'Quelle est la différence entre l\'ordonnateur et le comptable public ?', tips:['Ordonnateur : engage, liquide, ordonne les dépenses (élu ou DG délégué)','Comptable : exécute le paiement, contrôle la régularité (fonctionnaire État-DDFIP)','Incompatibilité totale de ces deux fonctions (separation des pouvoirs financiers)','Comptable : responsabilité personnelle et pécuniaire','Régime d\'apurement administratif (CAC → CRTC depuis 2022)'] },
  { cat:'finances', diff:1, question:'Qu\'est-ce que la DGF (Dotation Globale de Fonctionnement) ?', tips:['Principal concours financier de l\'État aux collectivités (~27 Md€/an)','Composante forfaitaire + composante de péréquation','Critères : population, superficie, longueur de voirie, potentiel fiscal','Péréquation : redistributive entre collectivités riches et pauvres','Tendance à la baisse depuis 2014 (contrainte budgétaire de l\'État)'] },
  { cat:'finances', diff:3, question:'Qu\'est-ce que l\'instruction budgétaire et comptable M57 ?', tips:['Référentiel comptable unifié applicable à toutes les collectivités depuis 2024','Remplace M14 (communes), M52 (départements), M71 (régions)','Rapprochement de la comptabilité privée','Introduction de la comptabilité analytique','Facilite la comparaison inter-collectivités et la consolidation des comptes'] },
  { cat:'finances', diff:2, question:'Quelles sont les principales ressources fiscales des collectivités ?', tips:['Taxes foncières sur les propriétés bâties et non bâties','CFE (Cotisation Foncière des Entreprises) remplace TP','TVA partagée : remplace la CVAE depuis 2023','Droits de mutation (DMTO) : sur les transactions immobilières','En Martinique + octroi de mer (~200 M€/an)'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce qu\'un débat d\'orientations budgétaires (DOB) ?', tips:['Présentation par l\'exécutif des grandes orientations avant le BP','Obligatoire pour les communes >3 500 hab, départements, régions','2 mois avant le vote du budget primitif','Permet le débat politique avant la décision finale','Rapport présenté à l\'assemblée délibérante, publicité requise'] },
  { cat:'finances', diff:2, question:'Comment fonctionne le contrôle de la Chambre Régionale des Comptes ?', tips:['Contrôle de la régularité des comptes (juridictionnel) : condamne le comptable si manquement','Examen de la gestion : recommandations sur l\'efficience','Contrôle budgétaire (via le préfet) : déséquilibre, non-vote','Rapport d\'observations définitives (ROD) public','Suites : réponse obligatoire de la collectivité, plan d\'action'] },
  { cat:'finances', diff:1, question:'Qu\'est-ce qu\'un marché public ? Quels sont les seuils principaux ?', tips:['Contrat onéreux État/collectivité avec opérateur économique','Seuils 2024 : <40 000€ : procédure adaptée simplifiée ; 40 000-221 000€ : MAPA ; >221 000€ : appel d\'offres','Principes : égalité de traitement, transparence, mise en concurrence','CCAG (Cahier des Clauses Administratives Générales) : conditions standards','Acheteur public : obligation de reddition des comptes (PAO)'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce qu\'une délégation de service public (DSP) ?', tips:['Contrat par lequel une collectivité confie la gestion d\'un service à un tiers','Rémunération : exploitation du service (risque transféré)','Exemples : eau, transports, parking, stade','Procédure : publicité, mise en concurrence, rapport analyse des offres','Contrôle de légalité et budgétaire renforcés'] },
  { cat:'finances', diff:3, question:'Qu\'est-ce que la règle d\'or des finances locales ?', tips:['Section de fonctionnement : équilibre réel obligatoire','Section d\'investissement : peut être financée par l\'emprunt','Interdit le financement du fonctionnement par l\'emprunt','Contrôlé par le préfet et la CRC','Exception théorique : garanties d\'emprunt accordées à des tiers'] },
  { cat:'finances', diff:2, question:'Comment évaluez-vous la santé financière d\'une collectivité ?', tips:['Épargne brute : recettes fonctionnement - dépenses fonctionnement','Épargne nette : épargne brute - remboursement dette','Ratio de désendettement : dette / épargne brute (seuil d\'alerte : >12 ans)','Taux d\'autofinancement de l\'investissement','Évolution du fonds de roulement et trésorerie'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce que le principe de non-affectation des recettes ?', tips:['Principe d\'universalité budgétaire','Les recettes globales financent l\'ensemble des dépenses','Pas de recette dédiée spécifiquement à une dépense (en théorie)','Exceptions : fonds de concours, fonds européens avec co-financement obligatoire','Permet souplesse d\'utilisation des ressources'] },
  { cat:'finances', diff:3, question:'Expliquez les principales évolutions de la fiscalité locale depuis 2020.', tips:['Suppression de la taxe d\'habitation sur résidences principales (2020-2023)','Suppression de la CVAE (2024) remplacée par TVA partagée','CFE maintenue mais fragilisée par réduction base','Redistribution de TVA nationale aux collectivités : moins d\'autonomie fiscale','Critique : "jacobinisme fiscal" réduisant la liberté des élus locaux'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce que la procédure adaptée (MAPA) ?', tips:['Marché À Procédure Adaptée : seuil 40 000€ à 221 000€ (fournitures/services) ou 5,5 M€ (travaux)','Liberté dans le choix des modalités de mise en concurrence','Publicité adaptée à l\'objet et au montant','Négociation possible','Bonne pratique : demander au moins 3 devis'] },
  { cat:'finances', diff:1, question:'Qu\'est-ce que le budget primitif et le budget supplémentaire ?', tips:['Budget primitif (BP) : adopté avant le 1er janvier N, prévisions de l\'année entière','Budget supplémentaire (BS) : modification en cours d\'année (facultatif)','Décision modificative (DM) : ajustement ciblé de crédits','Budget doit être en équilibre réel','Transmission au préfet : 15 jours après le vote'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce qu\'un partenariat public-privé (PPP) / Contrat de Partenariat ?', tips:['Contrat global : conception, financement, réalisation, maintenance','Paiement différé : loyer versé par la collectivité','Avantage : pas d\'investissement initial massif','Risque : coût total plus élevé, engagement long terme (20-30 ans)','Contrôlé par le préfet et la CRC – utilisé avec prudence'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce que le contrôle interne dans une collectivité territoriale ?', tips:['Ensemble des dispositions pour maîtriser les risques financiers','Séparation des tâches, validations, procédures écrites','Audit interne : évaluation indépendante de l\'efficacité des contrôles','Recommandé par la CRC et nécessaire pour les grandes collectivités','Cartographie des risques financiers (corrup., erreur, fraude)'] },
  { cat:'finances', diff:3, question:'Qu\'est-ce que les ressources propres et pourquoi sont-elles importantes ?', tips:['Art. 72-2 Constitution : ressources propres déterminantes dans l\'ensemble des ressources','Recettes fiscales, produits domaniaux, tarification services','Indicateur d\'autonomie fiscale vs dépendance aux dotations d\'État','Tendance à la baisse avec suppressions de taxes locales','Enjeu politique : liberté de gestion des élus locaux'] },
  { cat:'finances', diff:2, question:'Comment fonctionnent les fonds européens dans une collectivité ?', tips:['Programmation pluriannuelle 2021-2027 : FEDER, FSE+, FEADER, FEM','Autorité de gestion : Région (ou CTM en Martinique)','Appels à projets : critères d\'éligibilité et de sélection','Co-financement obligatoire (30-50% fonds propres)','Contrôle renforcé : irrégularités → remboursements','Rapport d\'exécution annuel'] },
  { cat:'finances', diff:1, question:'Qu\'est-ce qu\'une subvention et quelles sont les règles de base ?', tips:['Aide financière de l\'employeur public à un organisme tiers (association, collectivité)','Motif : intérêt général, non concurrence avec le secteur marchand','Convention obligatoire >23 000€','Rapport sur l\'utilisation des fonds (reddition de comptes)','Contrôle : justificatifs de dépenses, audit si montant important'] },
  { cat:'finances', diff:3, question:'Expliquez la notion de dépenses obligatoires pour les communes.', tips:['Dépenses que la loi impose aux collectivités (CGCT)','Exemples : rémunération du personnel, eau/assainissement, état civil','Si non-inscrites au budget : le préfet peut les inscrire d\'office','Contrôle de la CRC sur la liste des dépenses obligatoires','Distinction : dépenses obligatoires vs dépenses facultatives (potestatives)'] },
  { cat:'finances', diff:2, question:'Qu\'est-ce que la péréquation financière ?', tips:['Redistribution entre collectivités riches et pauvres','Péréquation verticale : État → collectivités via dotations (DSR, DSU)','Péréquation horizontale : entre collectivités (FPIC, FSRIF)','Critères : potentiel fiscal, effort fiscal, richesse relative','Objectif constitutionnel : "égalité des chances"'] },

  /* ── ACTUALITÉS TERRITORIALES (25) ──────────────────────── */
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la loi "Engagement et Proximité" de 2019 et ses apports ?', tips:['Loi du 27 décembre 2019 pour la commune et la démocratie locale','Renforcement du rôle des communes dans les EPCI','Droit de retrait facilité pour certaines compétences (eau, assainissement jusqu\'en 2026)','Pacte de gouvernance obligatoire','Création des conférences des maires dans les EPCI'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la loi 3DS (2022) et ses principales mesures ?', tips:['Loi du 21 février 2022 relative à la différenciation, décentralisation, déconcentration et simplification','Transferts optionnels aux régions : gestion des routes nationales','Renforcement de l\'expérimentation locale','Simplification des procédures d\'autorisation','Réformes sectorielles : logement social, eau, mobilité'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la politique ZAN (Zéro Artificialisation Nette) ?', tips:['Objectif : diviser par 2 la consommation d\'espaces naturels d\'ici 2031','Puis ZAN total d\'ici 2050','Inscrit dans loi Climat-Résilience 2021 (art. 194)','Impact sur les PLU, SCoT, SRADDET','Défi pour les communes : concilier développement et préservation foncière'] },
  { cat:'actualite', diff:1, question:'Qu\'est-ce que France Travail (ex-Pôle Emploi) ?', tips:['Nouveau nom depuis le 1er janvier 2024','Renforcement de la coordination avec les acteurs locaux (CAF, MSA, CTM)','Mission élargie : accompagnement de tous les publics (pas seulement chômeurs indemnisés)','Réseau d\'acteurs de l\'emploi unifié sous un même guichet','Réforme du RSA : conditionnalité à l\'accompagnement emploi'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la loi "Plein Emploi" de 2023 ?', tips:['Loi du 18 décembre 2023 pour le plein emploi','Objectif : taux de chômage <5% à horizon 2027','Réforme du RSA : bénéficiaires accompagnés obligatoirement (15-20h/sem)','France Travail : nouveau réseau unifié','Impact collectivités : co-animatrices du réseau emploi local'] },
  { cat:'actualite', diff:2, question:'Quelles sont les grandes orientations de la politique nationale de cohésion des territoires ?', tips:['Agence Nationale de la Cohésion des Territoires (ANCT) créée en 2020','Programme Action Cœur de Ville (villes moyennes)','Petites Villes de Demain','Programme Nouveaux Lieux Nouveaux Liens (ruralité)','France Très Haut Débit (THD) : couverture numérique universelle'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que le PCAET et pourquoi est-il important ?', tips:['Plan Climat-Air-Énergie Territorial','Obligatoire pour les EPCI >20 000 hab','Diagnostic énergie-climat du territoire','Objectifs de réduction des GES, d\'efficacité énergétique, d\'ENR','Contribution locale aux objectifs nationaux (neutralité carbone 2050)'] },
  { cat:'actualite', diff:1, question:'Qu\'est-ce que la transformation numérique des collectivités ?', tips:['Dématérialisation des services publics (dossiers administratifs en ligne)','Programme Action Publique 2022 → Services Publics +','Cybersécurité : enjeu majeur (attaques ransomware en hausse)','Intelligence artificielle dans les services locaux','Interopérabilité des systèmes d\'information'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la politique de la ville et quels sont les QPV ?', tips:['Politique ciblée sur les Quartiers Prioritaires de la politique de la Ville','~1 500 QPV en France métropolitaine + Outre-Mer','Contrats de Ville (ANRU, ANLHI) : rénovation urbaine et sociale','Crédits fléchés : ANRU (logement), BOP 147 (social)','Évaluation régulière : réaffectation des QPV tous les 6 ans'] },
  { cat:'actualite', diff:3, question:'Expliquez les enjeux du vieillissement de la population pour les collectivités.', tips:['Augmentation des besoins en EHPAD, services à domicile (SAAD)','Compétence département : APA (Allocation Personnalisée d\'Autonomie)','Financement : 5ème risque assurance maladie (CNSA)','Adaptation des logements et espaces publics (accessibilité)','Spécificité Martinique : vieillissement ultra-accéléré, brain drain des actifs'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la réforme des retraites de 2023 et ses impacts sur les fonctionnaires ?', tips:['Loi du 14 avril 2023 : âge légal porté à 64 ans (vs 62)','Durée de cotisation : 43 ans pour taux plein (dès 2027)','Fonctionnaires : même âge légal mais catégorie active maintient des avantages','Retraite progressive facilitée','Impact RH collectivités : allongement des carrières, adaptation GPEEC'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la loi Lemaire (République Numérique) 2016 et ses impacts ?', tips:['Loi du 7 octobre 2016 pour une République Numérique','Open Data : publication obligatoire des données publiques','Neutralité du net garantie','Accessibilité numérique : sites publics obligatoirement accessibles','Droit à l\'autodétermination informationnelle'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que l\'ANCT et quel est son rôle ?', tips:['Agence Nationale de la Cohésion des Territoires (2020)','Fusionner CGET, Epareca, Agence du Numérique','Ingénierie territoriale aux collectivités les plus fragiles','Co-financement des projets de développement local','Présence dans chaque département via les préfets'] },
  { cat:'actualite', diff:1, question:'Qu\'est-ce que le service civique et son intérêt pour les collectivités ?', tips:['Engagement volontaire 6-12 mois pour les 16-25 ans (30 ans pour handicap)','Indemnité : ~600€/mois (financée par l\'Agence Service Civique)','Missions d\'intérêt général (social, environnement, sport, culture)','Collectivités : accueil de volontaires, missions définies','Complément aux missions permanentes, pas substitution d\'emploi'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la transition énergétique pour les collectivités et comment y contribuer ?', tips:['Objectif national : neutralité carbone 2050 (Stratégie Nationale Bas Carbone)','Plan Bâtiments Durables : rénovation du patrimoine communal','Énergie renouvelable : photovoltaïque sur toitures, géothermie','Mobilité verte : véhicules électriques, bornes de recharge','Achats publics durables : SPASER (Schéma de Promotion des Achats Socialement Responsables)'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la loi "Séparatisme" (2021) et son impact sur les collectivités ?', tips:['Loi du 24 août 2021 confortant le respect des principes de la République','Renforcement des obligations de neutralité et de laïcité','Contrôle renforcé des associations bénéficiant de subventions publiques','Contrat d\'engagement républicain pour les associations','Impact : vérification systématique avant toute subvention'] },
  { cat:'actualite', diff:3, question:'Qu\'est-ce que la loi "Industrie Verte" de 2023 et ses impacts pour les collectivités ?', tips:['Loi du 23 octobre 2023 pour accélérer la réindustrialisation verte','Simplification des procédures d\'autorisation (permis unique)','Zones dédiées à l\'industrie dans les PLU','Réhabilitation de friches industrielles (financement Banque des Territoires)','Enjeu pour Martinique : pas de grande industrie mais économie circulaire'] },
  { cat:'actualite', diff:2, question:'Expliquez les enjeux du logement social pour les collectivités.', tips:['SRU : 25% de logements sociaux dans les communes >3 500 hab (loi 2000)','Rôle des bailleurs sociaux (OPH, ESH)','Financement : fonds propres collectivités + prêts CDC','Enjeu Martinique : vétusté du parc, bidonvilles, logements indécents','CTM : compétence logement + fonds européens FEDER'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la politique d\'attractivité territoriale ?', tips:['Attirer entreprises, populations, touristes, talents','Leviers : qualité de vie, services publics, foncier disponible, fiscalité','Marketing territorial : image, communication, réseaux','Agences de développement économique locales','En Martinique : attractivité contrainte par éloignement, coût de la vie, emploi'] },
  { cat:'actualite', diff:1, question:'Qu\'est-ce que le RSA (Revenu de Solidarité Active) ?', tips:['Allocation sous conditions de ressources pour les personnes en situation de précarité','Montant 2024 : ~635€/mois (personne seule)','Géré par le département (ou CTM en Martinique)','Bénéficiaires : 4 millions de personnes en France','Réforme 2023 : conditionnalité à l\'accompagnement vers l\'emploi'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la commande publique responsable et comment l\'appliquer ?', tips:['Insertion de clauses sociales et environnementales dans les marchés','Loi AGEC 2020 : objectifs de réemploi, de réparation','SPASER obligatoire pour les acheteurs >100 M€/an de marchés','Critères d\'attribution pondérés : 30-50% pour la valeur verte/sociale','Formation des acheteurs publics à la commande durable'] },
  { cat:'actualite', diff:3, question:'Quels sont les enjeux du RGPD pour les collectivités territoriales ?', tips:['RGPD : Règlement Général sur la Protection des Données (UE, mai 2018)','DPD obligatoire (Délégué à la Protection des Données) pour les collectivités','Registre des traitements de données obligatoire','Droits des usagers : accès, rectification, effacement, portabilité','Sanctions CNIL : avertissements à amendes (max 20M€ ou 4% CA mondial)'] },
  { cat:'actualite', diff:2, question:'Qu\'est-ce que la démocratie participative locale et ses limites ?', tips:['Consultation des habitants avant décisions (concertation, enquête publique)','Référendum local (art. 72-1 Constitution)','Budget participatif : associer les citoyens à l\'allocation de crédits','Limites : fatigue participative, représentativité limitée','Obligation : PPRI, ZAC, PLU soumis à enquête publique'] },
  { cat:'actualite', diff:1, question:'Qu\'est-ce que l\'accessibilité universelle des ERP et les enjeux pour les collectivités ?', tips:['ERP : Établissements Recevant du Public','Obligation de mise en accessibilité (loi 2005 + Agenda d\'Accessibilité Programmée 2014)','Commune : mairie, école, gymnase','Coût important pour les petites collectivités','Sanctions si non-conformité (amende, refus de subventions)'] },

  /* ── MISES EN SITUATION ORALES (47) ─────────────────────── */
  { cat:'situation', diff:2, question:'Vous êtes Attaché aux RH. Un agent cadre A vous informe que son supérieur lui a demandé de falsifier un rapport financier. Quelle est votre réaction ?', tips:['Écoute bienveillante et sans jugement immédiat','Recueil des faits précis (qui, quoi, quand, preuves)','Rappel des obligations déontologiques des deux agents','Alerter le DGS et le Directeur des Finances','Protocole lanceur d\'alerte (loi Sapin II, CGFP art. L135-1 ss)','Protection fonctionnelle de l\'agent signalant'] },
  { cat:'situation', diff:2, question:'Vous êtes chargé d\'un marché public informatique à 150 000€. Un élu vous appelle pour recommander l\'entreprise de son beau-frère. Comment réagissez-vous ?', tips:['Cadre légal : interdiction de favoritisme (art. 432-14 Code pénal)','Refus clair et motivé des instructions illicites','Documenter l\'appel (compte-rendu écrit)','Informer le DGS par écrit','Procédure de marché : impartialité totale du jury de sélection','Signalement possible à la HATVP si pression persiste'] },
  { cat:'situation', diff:3, question:'Un service que vous dirigez accumule un retard important sur un projet financé par l\'Europe. Les délais de justification arrivent. Comment gérez-vous ?', tips:['Diagnostic immédiat : causes du retard (RH, technique, partenarial)','Communication à l\'autorité de gestion (CTM/SGAR) sans délai','Demande de prolongation formelle auprès de l\'UE si possible','Plan de rattrapage : ressources additionnelles, réorganisation','Justifier les dépenses réalisées (prévenir les récupérations)','Leçons à tirer pour les futurs projets européens'] },
  { cat:'situation', diff:2, question:'Vous êtes chargé de la communication d\'une crise sanitaire (contamination à la légionelle dans un ERP géré par la collectivité). Comment communiquez-vous ?', tips:['Cellule de crise immédiate : DGS, DRH, direction technique, communication','Communication aux usagers dans les 24h (transparence)','Information préfecture et ARS sans délai','Mesures d\'urgence : fermeture temporaire, décontamination','Point presse : factuel, sans polémique, centré sur la sécurité','Suivi des procédures et retour à la normale communiqué'] },
  { cat:'situation', diff:2, question:'Le bilan financier de mi-année montre un dépassement de 15% sur le budget de fonctionnement de votre direction. Que faites-vous ?', tips:['Analyse des causes : dépenses imprévues, erreurs de prévision, recettes manquantes','Réunion d\'arbitrage avec le directeur et le contrôleur de gestion','Mesures correctives : gel de crédits non engagés, report de dépenses','Compte-rendu à la Direction des Finances','Decision modificative (DM) si nécessaire','Plan d\'action pour éviter que cela se reproduise'] },
  { cat:'situation', diff:3, question:'Vous devez fusionner deux services suite à une réorganisation. Des résistances fortes existent. Comment conduisez-vous ce changement ?', tips:['Diagnostic participatif : comprendre les peurs et résistances réelles','Communication transparente sur le pourquoi de la fusion','Groupes de travail mixtes sur l\'organisation future','Formation pour acquérir les nouvelles compétences','Désignation d\'un référent changement (manager ou pair)','Évaluation à 6 mois et ajustements'] },
  { cat:'situation', diff:2, question:'Un agent contractuel (CDI) de votre équipe multiplie les retards et est souvent en conflit avec les collègues. Quelles mesures prenez-vous ?', tips:['1. Entretien individuel : comprendre les causes, fixer des objectifs clairs','2. Formaliser un plan d\'amélioration (PAP) signé','3. Avertissement écrit si pas d\'amélioration','4. Entretien préalable au licenciement (avec DRH)','5. Si insuffisance professionnelle confirmée : procédure de licenciement contractuel','6. Médecin de prévention si cause médicale suspectée'] },
  { cat:'situation', diff:2, question:'Un citoyen vous interpelle sur les réseaux sociaux en publiant une photo d\'un dépôt sauvage d\'ordures devant un groupe scolaire. Comment réagissez-vous ?', tips:['Réponse rapide et publique : prise en charge assurée','Signalement interne au service espaces verts/propreté','Ramassage sous 24-48h','Information publique du citoyen sur les suites données','Vérification si récurrence : renforcer la signalétique, caméra de surveillance','Ne pas entrer dans la polémique politique sur les réseaux'] },
  { cat:'situation', diff:3, question:'Vous devez préparer une délibération pour le conseil municipal sur l\'attribution d\'une subvention importante à une association. Quels sont les points de contrôle ?', tips:['Vérification de l\'objet social de l\'association (intérêt général)','Montant > 23 000€ : convention obligatoire','Rapport sur l\'utilisation des subventions précédentes','Vote à bulletins secrets si demandé','Transmission au préfet dans les 15 jours','Publicité (affichage, site web) et transparence'] },
  { cat:'situation', diff:2, question:'Un agent de votre service vous informe qu\'il est victime de discrimination lors de l\'avancement. Comment traitez-vous cette situation ?', tips:['Écoute sans jugement, confidentialité garantie','Vérification des dossiers d\'avancement : critères objectifs documentés','Consultation des délibérations et du tableau d\'avancement','Rôle de la CAP (Commission Administrative Paritaire)','Si discrimination avérée : correction + signalement DGALN/DILCRAH','Défenseur des droits : l\'agent peut saisir indépendamment'] },
  { cat:'situation', diff:2, question:'Vous devez présenter le budget de votre direction à l\'exécutif. Comment le préparez-vous ?', tips:['Bilan de l\'exécution N-1 (dépenses réelles vs prévisions)','Besoins identifiés pour N+1 (projets, personnel, fonctionnement)','Arbitrage interne avant présentation','Présentation claire : fonctionnement/investissement, évolutions','Anticiper les questions sur les économies possibles','Chiffres clés : coût/bénéfice des projets d\'investissement'] },
  { cat:'situation', diff:3, question:'Un audit interne révèle des irrégularités dans les procédures de marchés publics de votre direction. Comment réagissez-vous ?', tips:['Suspension des procédures en cours si nécessaire','Information immédiate du DGS et du directeur des finances','Revue complète des marchés passés (3 dernières années)','Mise en place de procédures correctrices (contrôle interne)','Formation des agents aux procédures marchés','Signalement à la CRC/préfet si suspicion d\'irrégularité pénale'] },
  { cat:'situation', diff:2, question:'La CTM vous demande de mettre en place un dispositif d\'accueil des réfugiés climatiques. Quelle démarche adoptez-vous ?', tips:['Diagnostic : combien de personnes, durée, besoins','Coordination avec les services sociaux, l\'État (préfecture), les associations','Hébergement d\'urgence : mobilisation du parc disponible','Accompagnement social : droits, langue, insertion','Communication interne et externe (presse, usagers)','Plan de financement : État, fonds européens, ressources propres'] },
  { cat:'situation', diff:2, question:'Vous organisez une enquête publique sur un PLU modificatif. Quelles sont vos obligations ?', tips:['Désignation du commissaire enquêteur par le TA','Publication dans 2 journaux + affichage + site internet','Dossier complet à disposition du public','Réunion publique obligatoire dans certains cas','Registre de observations à analyser','Rapport du commissaire et délibération finale du conseil'] },
  { cat:'situation', diff:3, question:'Un élu vous demande d\'accélérer une décision administrative qui normalement nécessite une consultation préalable. Que faites-vous ?', tips:['Rappel clair des obligations légales et des délais incompressibles','Explication des risques juridiques d\'un vice de procédure','Proposition d\'alternatives légales pour accélérer','Trace écrite de la demande et de votre réponse','Si pression persiste : information du DGS','Refus de passer outre les délais de consultation obligatoires'] },
  { cat:'situation', diff:2, question:'Vous êtes en charge d\'un projet de création d\'une maison de services au public. Comment montez-vous ce projet ?', tips:['Étude de besoins : quels services, quels publics, quelle fréquentation attendue','Partenariats : CAF, CGSS, La Poste, France Travail, MSA','Financement : DETR, DSIL, fonds Maison France Services (ANCT)','Choix d\'un local accessible (accessibilité PMR)','Recrutement et formation des agents d\'accueil polyvalents','Évaluation à 1 an : fréquentation, satisfaction, coût'] },
  { cat:'situation', diff:2, question:'Votre service doit passer en open space. Une partie des agents s\'y oppose. Comment gérez-vous ?', tips:['Comprendre les raisons de l\'opposition (bruit, concentration, confidentialité)','Associer les agents à l\'aménagement (comité de projet)','Consultation du médecin de prévention + CST','Aménagements pour atténuer les nuisances (îlots, cloisons, zones de silence)','Charte de l\'open space : règles de comportement partagées','Plan de mobilisation post-déménagement'] },
  { cat:'situation', diff:3, question:'Vous devez rédiger une note à destination du DGS sur les impacts de la réforme de la formation professionnelle. Structurez votre réponse.', tips:['Objet : clair et précis en quelques mots','Introduction : contexte et problématique','Partie 1 : impacts sur les agents (droits, procédures)','Partie 2 : impacts sur la collectivité (coût, CNFPT, plan de formation)','Partie 3 : recommandations et propositions','Conclusion : délai de mise en conformité','Annexes : textes de référence'] },
  { cat:'situation', diff:2, question:'Décrivez comment vous organiseriez une journée d\'accueil des nouveaux agents.', tips:['Programme structuré de 9h à 17h','Accueil par le DGS ou DGA (mot d\'introduction sur la collectivité)','Présentation des services : tour de la collectivité','Remise des documents : règlement intérieur, chartes, organigramme','Présentation des outils informatiques (SI RH, messagerie)','Échanges informels avec les équipes','Attribution d\'un tuteur/référent pour les premiers mois'] },
  { cat:'situation', diff:2, question:'Un agent vous signale avoir subi une agression verbale d\'un usager en accueil. Comment traitez-vous cela ?', tips:['Écoute immédiate et soutien moral','Protection fonctionnelle : engagement immédiat de l\'employeur','Dépôt de plainte : accompagnement de l\'agent si souhaité','Prise en charge psychologique si traumatisme','Enquête interne : circonstances, témoins','Mesures préventives : formation gestion de l\'agressivité, alarme, agent binôme'] },
  { cat:'situation', diff:3, question:'Vous devez piloter l\'évaluation de la politique d\'insertion de la CTM. Quelle méthodologie appliquez-vous ?', tips:['Définir les questions évaluatives : objectifs atteints ? Efficience ?','Collecte des données : indicateurs prédéfinis, entretiens, focus groups','Comparaison avec d\'autres territoires (benchmarking)','Rapport d\'évaluation : constats, conclusions, recommandations','Présentation à l\'assemblée délibérante','Plan d\'action d\'amélioration basé sur les recommandations'] },
  { cat:'situation', diff:2, question:'Un projet de réhabilitation d\'équipement sportif est confronté à un glissement de terrain. Que faites-vous ?', tips:['Sécurisation immédiate du site (interdiction d\'accès)','Déclaration au bureau d\'études géotechniques','Information du maire/président et assurance','Expertise technique obligatoire avant toute reprise de travaux','Communication aux riverains et usagers concernés','Révision du calendrier et du budget + information de la CRC si dépassement'] },
  { cat:'situation', diff:2, question:'Comment gérez-vous la communication d\'une décision impopulaire (fermeture d\'une école) ?', tips:['Argumentation factuelle et transparente (démographie, coût)','Consultation préalable des parents et de la communauté scolaire','Alternatives proposées : regroupement scolaire, transport, maintien services','Réunion publique : écouter les oppositions, répondre aux questions','Communication officielle : courrier, site web, presse locale','Accompagnement post-décision : soutien aux familles'] },
  { cat:'situation', diff:3, question:'Un rapport de la Cour des comptes pointe des anomalies dans votre collectivité. Quelle est la procédure ?', tips:['Réception du rapport d\'observations provisoires : 2 mois pour répondre','Réponse de l\'ordonnateur : factuelle, documentée, constructive','Rapport définitif : publication obligatoire (site web collectivité)','Rapport de suivi à 2 ans','Plan d\'action correctif : mesures, responsables, délais','Communication interne (conseil, services) et externe (presse si nécessaire)'] },
  { cat:'situation', diff:2, question:'Vous êtes chargé de réduire les délais de traitement des demandes d\'APA (Allocation Personnalisée d\'Autonomie). Comment y parvenir ?', tips:['Cartographie du processus actuel : identifier les goulots d\'étranglement','Délai légal de l\'APA : 2 mois (alerte si dépassement)','Ressources supplémentaires : renforts humains, outils dématérialisés','Formation des instructeurs','Coordination avec les équipes médico-sociales (EMS)','Indicateurs de suivi hebdomadaire et objectifs clairs'] },
  { cat:'situation', diff:2, question:'Comment établiriez-vous un plan de continuité d\'activité (PCA) pour votre service ?', tips:['Identification des activités critiques (ne pouvant pas s\'interrompre)','Scénarios de crise : cyberattaque, catastrophe naturelle, pandémie','Mesures de continuité : procédures manuelles, télétravail, sites de repli','Ressources minimales nécessaires (personnel, informatique)','Test du PCA (exercice simulé 1× par an)','Mise à jour annuelle'] },
  { cat:'situation', diff:3, question:'Un journaliste vous interroge sur un scandale potentiel dans votre direction. Comment répondez-vous ?', tips:['Ne pas improviser : recueillir les faits avant toute communication','Informer le DGS et le cabinet du président','Communication officielle coordonnée avec le service presse','Principe : transparence sur les faits avérés, silence sur ce qui est sous enquête','Pas de déclaration personnelle : la collectivité parle d\'une voix','Si enquête judiciaire : "ne pas commenter une affaire judiciaire en cours"'] },
  { cat:'situation', diff:2, question:'Vous devez organiser des élections des délégués du personnel au CST. Quelle procédure ?', tips:['Affichage des dates d\'élection 60 jours avant','Listes électorales : agents titulaires et contractuels de droit public éligibles','Dépôt de listes syndicales 35 jours avant','Matériel de vote : préparation et envoi par voie électronique ou papier','Dépouillement : représentants employeur + représentants syndicaux','Proclamation des résultats et transmission au préfet'] }

]; // fin BANQUE_JURY

/* --- Injection de la section HTML Banque de questions --- */
(function() {
  const container = document.querySelector('.main-content');
  if (!container) return;

  const categories = [
    { val: 'all', label: 'Toutes (210)' },
    { val: 'motivation', label: 'Motivation & projet' },
    { val: 'territorial', label: 'Environnement territorial' },
    { val: 'martinique', label: 'Martinique & CTM' },
    { val: 'rh', label: 'RH & Management' },
    { val: 'finances', label: 'Finances publiques' },
    { val: 'actualite', label: 'Actualités territoriales' },
    { val: 'situation', label: 'Mises en situation' }
  ];

  /* Compter par catégorie */
  const counts = {};
  window.BANQUE_JURY.forEach(q => { counts[q.cat] = (counts[q.cat] || 0) + 1; });

  const section = document.createElement('section');
  section.id = 'banque-jury';
  section.className = 'page-section';
  section.innerHTML = `
    <div class="banque-header">
      <h1>🎯 Banque de questions de jury</h1>
      <p>${window.BANQUE_JURY.length} questions réparties en ${Object.keys(counts).length} thématiques · Avec éléments de réponse détaillés</p>
    </div>
    <div class="bj-filters" id="bj-filter-btns">
      ${categories.map(c => {
        const n = c.val === 'all' ? window.BANQUE_JURY.length : (counts[c.val] || 0);
        return `<button class="bj-filter-btn${c.val === 'all' ? ' active' : ''}" data-cat="${c.val}">${c.label} <small>(${n})</small></button>`;
      }).join('')}
    </div>
    <div class="bj-grid" id="bj-questions-grid"></div>
  `;
  container.appendChild(section);

  function renderQuestions(cat) {
    const grid = document.getElementById('bj-questions-grid');
    if (!grid) return;
    const list = cat === 'all' ? window.BANQUE_JURY : window.BANQUE_JURY.filter(q => q.cat === cat);
    grid.innerHTML = list.map((q, i) => {
      const stars = '⭐'.repeat(q.diff || 1) + '☆'.repeat(3 - (q.diff || 1));
      return `<div class="bj-item">
        <div class="bj-item-header" onclick="this.nextElementSibling.classList.toggle('show'); this.querySelector('.bj-toggle-btn').textContent = this.nextElementSibling.classList.contains('show') ? '▲' : '▼'">
          <span class="bj-cat">${q.cat}</span>
          <span class="bj-q-text">${q.question}</span>
          <span class="bj-diff" title="Difficulté">${stars}</span>
          <button class="bj-toggle-btn" aria-label="Afficher la réponse">▼</button>
        </div>
        <div class="bj-answer">
          <strong>Éléments clés à aborder :</strong>
          <ul>${(q.tips || []).map(t => `<li>${t}</li>`).join('')}</ul>
          ${q.exemple ? `<div class="bj-exemple-oral">💬 <em>${q.exemple}</em></div>` : ''}
        </div>
      </div>`;
    }).join('');
  }

  renderQuestions('all');

  document.addEventListener('click', function(e) {
    const btn = e.target.closest('.bj-filter-btn');
    if (!btn) return;
    document.querySelectorAll('.bj-filter-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    renderQuestions(btn.dataset.cat);
  });

})();
